# Generated by Django 5.0.4 on 2024-04-30 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moves", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="number_of_sides",
        ),
        migrations.AddField(
            model_name="game",
            name="board_side_length",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="move",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="moves",
                to="moves.game",
            ),
        ),
    ]
